post http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYzZjM5NzFhZWZmZTJiY2Q2N2VjODlmNiIsImlhdCI6MTY3NjkwOTM2OCwiZXhwIjoxNjc2OTEyOTY4fQ.A5J9CwR1Cc4apEajfPsAE5xl6uJ5qk1LewncddRgAo8
Content-Type: application/json

{
  "title": "this is working",
  "author": "tuomas",
  "url": "/first-blog-post",
  "user": "63f3971aeffe2bcd67ec89f6",
  "likes": 0
}